export const orgDataList = [
  {
    code: '00100101',
    pId: '001001',
    principalName: null,
    isLeaf: '1',
    isUsed: 'Y',
    isLowest: '1',
    principal: null,
    chargePrincipalName: null,
    officePhone: null,
    ordIndex: 0,
    codeName: '00100101 三级部门[启用]',
    name: '三级部门',
    chargePrincipal: null,
    id: '00100101',
  },
  {
    code: '010',
    pId: '0',
    principalName: 'CS0002',
    isLeaf: '1',
    isUsed: 'Y',
    isLowest: '1',
    principal: 'CS0002',
    chargePrincipalName: '王某666',
    officePhone: null,
    ordIndex: 0,
    codeName: '010 森林部门[启用]',
    name: '森林部门',
    chargePrincipal: '0666',
    id: '010',
  },
  {
    code: '011',
    pId: '0',
    principalName: null,
    isLeaf: '1',
    isUsed: 'N',
    isLowest: '1',
    principal: null,
    chargePrincipalName: null,
    officePhone: null,
    ordIndex: 0,
    codeName: '011 011[停用]',
    name: '011',
    chargePrincipal: null,
    id: '011',
  },
  {
    code: '235',
    pId: '0',
    principalName: null,
    isLeaf: '1',
    isUsed: 'Y',
    isLowest: '1',
    principal: null,
    chargePrincipalName: null,
    officePhone: null,
    ordIndex: 0,
    codeName: '235 测试助记码部门[启用]',
    name: '测试助记码部门',
    chargePrincipal: null,
    id: '235',
  },
  {
    code: '300',
    pId: '0',
    principalName: '王某600',
    isLeaf: '0',
    isUsed: 'Y',
    isLowest: '1',
    principal: '0600',
    chargePrincipalName: '王某601',
    officePhone: null,
    ordIndex: 0,
    codeName: '300 业务部[启用]',
    name: '业务部',
    chargePrincipal: '0601',
    id: '300',
  },
  {
    code: '999',
    pId: '0',
    principalName: '王某601',
    isLeaf: '1',
    isUsed: 'Y',
    isLowest: '1',
    principal: '0601',
    chargePrincipalName: '王某602',
    officePhone: null,
    ordIndex: 0,
    codeName: '999 外单位人员部门[启用]',
    name: '外单位人员部门',
    chargePrincipal: '0602',
    id: '999',
  },
  {
    code: '005',
    pId: '0',
    principalName: null,
    isLeaf: '1',
    isUsed: 'N',
    isLowest: '1',
    principal: null,
    chargePrincipalName: null,
    officePhone: null,
    ordIndex: 1,
    codeName: '005 返聘人员部门[停用]',
    name: '返聘人员部门',
    chargePrincipal: null,
    id: '005',
  },
  {
    code: '002',
    pId: '0',
    principalName: '金伯中',
    isLeaf: '1',
    isUsed: 'Y',
    isLowest: '1',
    principal: '0003',
    chargePrincipalName: '王某449',
    officePhone: null,
    ordIndex: 2,
    codeName: '002 科室一[启用]',
    name: '科室一',
    chargePrincipal: '0449',
    id: '002',
  },
  {
    code: '003',
    pId: '0',
    principalName: null,
    isLeaf: '1',
    isUsed: 'Y',
    isLowest: '1',
    principal: null,
    chargePrincipalName: null,
    officePhone: null,
    ordIndex: 2,
    codeName: '003 科室二[启用]',
    name: '科室二',
    chargePrincipal: null,
    id: '003',
  },
  {
    code: '001',
    pId: '0',
    principalName: null,
    isLeaf: '0',
    isUsed: 'Y',
    isLowest: '1',
    principal: '000000000000000000',
    chargePrincipalName: '王某449',
    officePhone: null,
    ordIndex: 3,
    codeName: '001 测试部门[启用]',
    name: '测试部门',
    chargePrincipal: '0449',
    id: '001',
  },
  {
    code: '001001',
    pId: '001',
    principalName: null,
    isLeaf: '0',
    isUsed: 'Y',
    isLowest: '1',
    principal: null,
    chargePrincipalName: null,
    officePhone: null,
    ordIndex: 3,
    codeName: '001001 2324[启用]',
    name: '2324',
    chargePrincipal: null,
    id: '001001',
  },
  {
    code: '233',
    pId: '0',
    principalName: null,
    isLeaf: '1',
    isUsed: 'Y',
    isLowest: '1',
    principal: null,
    chargePrincipalName: null,
    officePhone: null,
    ordIndex: 3,
    codeName: '233 高效部[启用]',
    name: '高效部',
    chargePrincipal: null,
    id: '233',
  },
  {
    code: '004',
    pId: '0',
    principalName: null,
    isLeaf: '1',
    isUsed: 'Y',
    isLowest: '1',
    principal: null,
    chargePrincipalName: null,
    officePhone: null,
    ordIndex: 4,
    codeName: '004 后勤部[启用]',
    name: '后勤部',
    chargePrincipal: null,
    id: '004',
  },
  {
    code: '012',
    pId: '0',
    principalName: null,
    isLeaf: '1',
    isUsed: 'Y',
    isLowest: '1',
    principal: null,
    chargePrincipalName: null,
    officePhone: null,
    ordIndex: 20,
    codeName: '012 收支产品开发部[启用]',
    name: '收支产品开发部',
    chargePrincipal: null,
    id: '012',
  },
  {
    code: '009',
    pId: '0',
    principalName: null,
    isLeaf: '1',
    isUsed: 'Y',
    isLowest: '1',
    principal: null,
    chargePrincipalName: null,
    officePhone: null,
    ordIndex: 30,
    codeName: '009 产品管理部[启用]',
    name: '产品管理部',
    chargePrincipal: null,
    id: '009',
  },
  {
    code: '001002',
    pId: '001',
    principalName: null,
    isLeaf: '1',
    isUsed: 'Y',
    isLowest: '1',
    principal: null,
    chargePrincipalName: null,
    officePhone: null,
    ordIndex: null,
    codeName: '001002 001002[启用]',
    name: '001002',
    chargePrincipal: null,
    id: '001002',
  },
  {
    code: '006',
    pId: '0',
    principalName: null,
    isLeaf: '1',
    isUsed: 'Y',
    isLowest: '1',
    principal: null,
    chargePrincipalName: null,
    officePhone: null,
    ordIndex: null,
    codeName: '006 外籍人员部门[启用]',
    name: '外籍人员部门',
    chargePrincipal: null,
    id: '006',
  },
  {
    code: '007',
    pId: '0',
    principalName: null,
    isLeaf: '1',
    isUsed: 'Y',
    isLowest: '1',
    principal: null,
    chargePrincipalName: null,
    officePhone: null,
    ordIndex: null,
    codeName: '007 测试人员导入的部门[启用]',
    name: '测试人员导入的部门',
    chargePrincipal: null,
    id: '007',
  },
  {
    code: '300000',
    pId: '300',
    principalName: null,
    isLeaf: '1',
    isUsed: 'Y',
    isLowest: '1',
    principal: null,
    chargePrincipalName: null,
    officePhone: null,
    ordIndex: null,
    codeName: '300000 业务部[启用]',
    name: '业务部',
    chargePrincipal: null,
    id: '300000',
  },
  {
    code: '300001',
    pId: '300',
    principalName: null,
    isLeaf: '1',
    isUsed: 'Y',
    isLowest: '1',
    principal: null,
    chargePrincipalName: null,
    officePhone: null,
    ordIndex: null,
    codeName: '300001 业务一部[启用]',
    name: '业务一部',
    chargePrincipal: null,
    id: '300001',
  },
  {
    code: '300002',
    pId: '300',
    principalName: null,
    isLeaf: '1',
    isUsed: 'Y',
    isLowest: '1',
    principal: null,
    chargePrincipalName: null,
    officePhone: null,
    ordIndex: null,
    codeName: '300002 业务二部[启用]',
    name: '业务二部',
    chargePrincipal: null,
    id: '300002',
  },
  {
    code: '300003',
    pId: '300',
    principalName: null,
    isLeaf: '1',
    isUsed: 'N',
    isLowest: '1',
    principal: null,
    chargePrincipalName: null,
    officePhone: null,
    ordIndex: null,
    codeName: '300003 业务三部[停用]',
    name: '业务三部',
    chargePrincipal: null,
    id: '300003',
  },
]
